version: '2.1'

services:
  client:
    image: client 
    build: client
    restart: always
    links:
      - server
    ports:
      - "4200:80"
    depends_on:
      - server
  server:
    image: server
    build: server
    environment:
       PORT : 8080
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo 
  # redis:
  #   image: redis
  #   volumes:
  #     - ./data:/data
  #   ports:
  #     - 6379
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb/db:/data/db