version: '2.1'

services:
  client:
    image: client 
    build: client
    restart: always
    links:
      - server
    ports:
      - "4200:80"
  server:
    image: server
    build: server
    environment:
       PORT : 8080
    restart: always
    ports:
       - 8080:8080 