version: '2.1'

services:
  client:
    image: client 
    build: client
    restart: always
    links:
      - server
    ports:
      - "4200:80"
    depends_on:
      - server
  server:
    image: server
    build: server
    environment:
       PORT : 8080
    restart: always
    ports:
      - 8080:8080
    links:
      - dbpostgres
    depends_on:
      dbpostgres:
        condition: service_healthy
  dbpostgres:
    image: postgres:10.3
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql
      - ./postgresStartup:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
